### ISSUE TITLE
Crash due to corrupted configuration file.

### ISSUE THREAD

**Issue by Sssniper** [Hyddwn/HyddwnLauncher#13]
Was playing with some of the mods from Abyss and client crashed. Trying to restart it I get this message from HyddwnLauncher.

```
5/5/2018 12:11:55 AM [Info] - === Application Startup ===
5/5/2018 12:11:55 AM [Info] - Initialize Launcher Context
5/5/2018 12:11:56 AM [Error] - Fatal error occured in application!
5/5/2018 12:11:56 AM [Exception] - System.NullReferenceException: Object reference not set to an instance of an object.
   at HyddwnLauncher.Core.LauncherSettingsManager..ctor()
   at HyddwnLauncher.Core.LauncherContext..ctor()
   at HyddwnLauncher.App.<OnStartup>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at HyddwnLauncher.App.Main()
   at HyddwnLauncher.Program.Main(String[] args)
```

**Comment by Seeker1437** [comment]
Taking a look at this now, thanks for the report!

**Comment by Seeker1437** [comment]
I was able to identify the issue. The workaround is to do the following:

Please go to **%localappdata%/Hyddwn Launcher** _(you can copy/paste that into the windows search or windows explorer)_ and delete the file named **configuration.json**.

Please reply here if you run into any issues.

**Comment by Seeker1437** [comment]
Additional report:

```
Date: 7/28/2018 12:19:33 PM
OS: Microsoft Windows NT 6.3.9600.0
Application Directory: C:\Nexon\Library\mabinogi\appdata\
Current Directory: C:\Nexon\Library\mabinogi\appdata
System Folder: C:\Nexon\Mabinogi
.NET Runtime: v4.0.30319
Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.
   at HyddwnLauncher.Core.LauncherSettingsManager..ctor()
   at HyddwnLauncher.Core.LauncherContext..ctor()
   at HyddwnLauncher.App.<OnStartup>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at HyddwnLauncher.App.Main()
   at HyddwnLauncher.Program.Main(String[] args)
```

**Comment by Seeker1437** [comment]
My first attempt at addressing this issue was with ae6d4eb which appear to not have corrected the issue fully, I will work on this to come up with a complete fix.

**Comment by Seeker1437** [comment]
I have updated the launcher with newer code that should resolve this issue, can you please test?

**Comment by Lordsithis1** [comment]
I am still getting this issue, i am going to try deleting the configuration.json and I will let you know if it still fixes the issue at least. only having an issue with once the patch is downloaded, it crashes.

**Comment by Seeker1437** [comment]
Closing due to age.
