### ISSUE TITLE
Unable to patch into 11.0.0 from 10.0.1

### ISSUE THREAD

**Issue by Lordsithis1** [Hyddwn/HyddwnLauncher#17]
I had no issues updating the launcher previously, but am unable to get it updated into 11.0 . I have restarted computer, even removed and reinstalled the launcher. This is the error that it gives me.

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

Date: 8/15/2018 1:42:29 PM
OS: Microsoft Windows NT 10.0.16299.0
Application Directory: C:\Nexon\Library\mabinogi\appdata\
Current Directory: C:\Nexon\Library\mabinogi\appdata
System Folder: C:\WINDOWS\system32
.NET Runtime: v4.0.30319
Exception Details: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at HyddwnLauncher.Model.Updator.DownloadUpdateCompleted(Boolean requiresRestart)
   at HyddwnLauncher.Model.Updator.<DownloadUpdate>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at HyddwnLauncher.App.Main()
   at HyddwnLauncher.Program.Main(String[] args)

**Comment by Seeker1437** [comment]
Please download this archive

http://launcher.hyddwnproject.com/public/files/update/U1200.zip

Drop the extracted file in the same folder that Hyddwn Launcher.exe resides.

This should resolve this issue.

**Comment by Lordsithis1** [comment]
Thank you, should I delete this?

**Comment by Seeker1437** [comment]
No need to delete. :)
