### ISSUE TITLE
can't login anymore

### ISSUE THREAD

**Issue by MelanieTanaka** [Hyddwn/HyddwnLauncher#30]
I closed mabi a few days ago, tried to play again today and I can't login, just says incorrect user or password.

I noticed a button that says there is an update so I did that. Now instead of an incorrect login I get the following crash error:

Launcher Version: 0.11.18.0
Date: 7/12/2019 6:40:48 PM
OS: Microsoft Windows NT 6.2.9200.0
Application Directory: C:\Program Files (x86)\Steam\steamapps\common\Mabinogi\hyddwn\Release\
Current Directory: C:\Program Files (x86)\Steam\steamapps\common\Mabinogi
System Folder: C:\Windows\system32
.NET Runtime: v4.0.30319
Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.
   at HyddwnLauncher.MainWindow.<LaunchOfficial>d__141.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at HyddwnLauncher.App.Main()
   at HyddwnLauncher.Program.Main(String[] args)

**Comment by Seeker1437** [comment]
Thanks for the report, I am looking into this issue for you now.

**Comment by Seeker1437** [comment]
Can you try the latest pre-release and let me know if you still have this issue?

https://github.com/Hyddwn/HyddwnLauncher/releases/download/v0.11.18-beta.21/HL01118-beta21.zip

**Comment by MelanieTanaka** [comment]
It is now trying to redownload all of mabinogi when I run it. I've never had this launcher do updates before and have been using it for over a year so that's a bit weird. I just let steam update the game.

[https://i.imgur.com/iCzIVm0.png](url)

**Comment by Seeker1437** [comment]
Yeah, you’re right I will make an adjustment to the launcher for this. Bare with me.

**Comment by Seeker1437** [comment]
Can you try the newest pre-release?

https://github.com/Hyddwn/HyddwnLauncher/releases/tag/v0.11.18-beta.22

**Comment by MelanieTanaka** [comment]
Seems to be working fine now, no patching and can log into the game.
Thank you.

**Comment by Seeker1437** [comment]
Perfect! Thanks for the report!
